import { chromium, expect } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
const chromePath = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const urlArgument = process.argv.indexOf('--url');
const gameURL = process.env.GAME_URL || (urlArgument >= 0 ? process.argv[urlArgument + 1] : 'http://localhost:5173/');
const audit = process.argv.includes('--audit');
const browser = await chromium.launch({ headless: true, args: audit ? ['--remote-debugging-port=9225'] : [], executablePath: process.env.PLAYWRIGHT_CHROME || (existsSync(chromePath) ? chromePath : undefined) });
if (audit) {
  const { default: lighthouse } = await import('lighthouse');
  const result = await lighthouse(gameURL, { port: 9225, output: ['html','json'], logLevel: 'error', onlyCategories: ['performance','accessibility','best-practices','seo'] });
  await writeFile('artifacts/lighthouse.report.html', result.report[0]);
  await writeFile('artifacts/lighthouse.report.json', result.report[1]);
  console.log(JSON.stringify({ scores: Object.fromEntries(Object.entries(result.lhr.categories).map(([key,category]) => [key,category.score * 100])), metrics: { LCP: result.lhr.audits['largest-contentful-paint'].displayValue, CLS: result.lhr.audits['cumulative-layout-shift'].displayValue }, failed: Object.values(result.lhr.audits).filter(item => item.score !== null && item.score < 1 && Array.isArray(item.details?.items)).map(item => ({ id: item.id, title: item.title, score: item.score, details: item.details.items.slice(0,3) })) }));
  await browser.close(); process.exit(0);
}
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const page = await context.newPage();
await page.clock.install();
const errors = [], responses = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
page.on('response', response => { if (response.status() >= 400) responses.push({ status: response.status(), url: response.url() }); });
await page.goto(gameURL);
await page.waitForSelector('body[data-ready="true"]', { timeout: 30000 });
if (process.argv.includes('--offline')) {
  await page.evaluate(async () => { await caches.open('other-game-cache'); await navigator.serviceWorker.register('./sw.js'); await navigator.serviceWorker.ready; });
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true);
  if (!await page.evaluate(() => caches.has('other-game-cache'))) throw new Error('Other game cache was removed');
  await context.setOffline(true); await page.reload(); await page.waitForSelector('body[data-ready="true"]');
  await page.setViewportSize({ width: 393, height: 852 });
  await page.getByRole('button', { name: '템페스트 선택', exact: true }).scrollIntoViewIfNeeded();
  await page.getByRole('button', { name: '템페스트 선택', exact: true }).click();
  await page.getByRole('button', { name: '경기 시작', exact: true }).click(); await page.waitForSelector('body[data-phase="rally"]');
  await page.screenshot({ path: 'artifacts/offline-game.png', fullPage: true });
  console.log(JSON.stringify({ offline: true, unrelatedCachePreserved: true, phase: await page.locator('body').getAttribute('data-phase'), errors, responses }));
  await writeFile('artifacts/offline-qa-results.json', JSON.stringify({ offline: true, unrelatedCachePreserved: true, errors, responses }, null, 2));
  await browser.close(); process.exit(0);
}
await page.screenshot({ path: 'artifacts/desktop-lobby.png', fullPage: true });
console.log(JSON.stringify({ title: await page.title(), errors, responses, roster: await page.locator('.roster-item').count() }));
await page.setViewportSize({ width: 393, height: 852 });
await page.screenshot({ path: 'artifacts/mobile-lobby.png', fullPage: true });
console.log(JSON.stringify(await page.evaluate(() => ({ viewport: innerHeight, width: innerWidth, bodyWidth: document.body.scrollWidth, height: document.documentElement.scrollHeight, arena: document.querySelector('#arena-wrap').getBoundingClientRect().toJSON() }))));
await page.getByRole('button', { name: '경기 시작', exact: true }).click();
await page.waitForSelector('body[data-phase="rally"]');
await page.screenshot({ path: 'artifacts/mobile-game.png', fullPage: true });
await page.getByRole('button', { name: '점프', exact: true }).click();
await page.waitForTimeout(150);
await page.getByRole('button', { name: '스파이크. 길게 눌렀다 놓으면 더 강하게 공격합니다.' }).click();
await page.getByRole('button', { name: '일시정지', exact: true }).click();
await page.screenshot({ path: 'artifacts/mobile-pause.png', fullPage: true });
console.log(JSON.stringify({ pause: await page.locator('#pause-dialog').evaluate(el => el.open), errors, responses }));
await page.getByRole('button', { name: '선수 선택으로', exact: true }).filter({ visible: true }).click();
const sizes = [[320,568], [320,720], [360,780], [393,852], [430,932], [844,390]];
const layouts = [];
for (const [width, height] of sizes) {
  await page.setViewportSize({ width, height });
  await page.screenshot({ path: `artifacts/lobby-${width}x${height}.png`, fullPage: true });
  layouts.push(await page.evaluate(() => ({ width: innerWidth, height: innerHeight, documentWidth: document.documentElement.scrollWidth, documentHeight: document.documentElement.scrollHeight, startVisible: document.querySelector('#mobile-start').getBoundingClientRect().bottom <= innerHeight })));
}
console.log(JSON.stringify({ layouts }));
await page.setViewportSize({ width: 393, height: 852 });
for (const name of ['노바','레이븐','발키리','바이퍼','엠버','아틀라스','세라프','링스','템페스트','오닉스']) {
  const button = page.getByRole('button', { name: `${name} 선택`, exact: true });
  await button.scrollIntoViewIfNeeded(); await button.click(); await expect(button).toHaveAttribute('aria-pressed', 'true');
}
await page.reload(); await page.waitForSelector('body[data-ready="true"]');
await expect(page.getByRole('button', { name: '오닉스 선택', exact: true })).toHaveAttribute('aria-pressed','true');
console.log('All 10 characters can be selected; selection persists after reload.');
await page.getByRole('button', { name: /함께 뛸 파트너:/ }).click();
await page.getByRole('button', { name: '게임 설정', exact: true }).click();
await page.locator('#music-setting').uncheck(); await page.locator('#sfx-setting').uncheck(); await page.locator('#assist-setting').uncheck();
await page.getByRole('button', { name: '설정 완료' }).click();
await page.reload(); await page.waitForSelector('body[data-ready="true"]');
await page.getByRole('button', { name: '게임 설정', exact: true }).click();
await expect(page.locator('#assist-setting')).not.toBeChecked();
await page.locator('#assist-setting').check(); await page.getByRole('button', { name: '설정 완료' }).click();
await page.getByRole('button', { name: '조작 방법' }).click();
await expect(page.locator('#help-dialog')).toBeVisible(); await page.keyboard.press('Escape');
await page.getByRole('button', { name: '경기 시작', exact: true }).click(); await page.waitForSelector('body[data-phase="rally"]');
await page.keyboard.press('Space'); await page.keyboard.down('KeyJ'); await page.waitForTimeout(300); await page.keyboard.up('KeyJ');
const stick = await page.locator('#joystick').boundingBox();
await page.mouse.move(stick.x + stick.width / 2, stick.y + stick.height / 2); await page.mouse.down(); await page.mouse.move(stick.x + stick.width - 5, stick.y + stick.height / 2);
await expect(page.locator('#joystick-thumb')).not.toHaveCSS('transform','none'); await page.mouse.up();
await page.getByRole('button', { name: '일시정지', exact: true }).click();
const pausedScore = await page.locator('#scoreboard').innerText(); await page.waitForTimeout(400); await expect(page.locator('#scoreboard')).toHaveText(pausedScore, { useInnerText: true });
await page.getByRole('button', { name: '경기 계속' }).click(); await expect(page.locator('#pause-dialog')).not.toBeVisible();
await page.getByRole('button', { name: '일시정지', exact: true }).click();
await page.getByRole('button', { name: '선수 선택으로', exact: true }).filter({ visible: true }).click();
await page.getByRole('button', { name: /빠른 경기.*변경/ }).click();
await page.getByRole('button', { name: /타이밍 연습.*60초 동안 실력 다지기/ }).click();
await page.getByRole('button', { name: '경기 시작', exact: true }).click();
await page.clock.runFor(61000);
await expect(page.locator('#result-dialog')).toBeVisible({ timeout: 10000 });
await expect(page.locator('#result-title')).toHaveText('한 번 더, 더 정확하게.');
await page.screenshot({ path: 'artifacts/training-result.png', fullPage: true });
console.log('Real browser practice finishes and opens the result screen.');
await page.getByRole('button', { name: '선수 선택으로', exact: true }).filter({ visible: true }).click();
await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
await page.screenshot({ path: 'artifacts/mobile-dark.png', fullPage: true });
await page.setViewportSize({ width: 1440, height: 1000 });
await page.screenshot({ path: 'artifacts/desktop-dark.png', fullPage: true });
await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'no-preference' });
await page.screenshot({ path: 'artifacts/desktop-lobby.png', fullPage: true });
await writeFile('artifacts/browser-qa-results.json', JSON.stringify({ errors, responses, layouts, checked: ['10 original characters','keyboard movement and jump','charge button','joystick pointer capture','pause and resume','persistent character and settings','help modal','60 second practice and result','dark mode','reduced motion'] }, null, 2));
if(errors.length || responses.length) throw new Error(JSON.stringify({errors,responses}));
await browser.close();
